/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PForm: typeof import('./src/components/global/structure/PForm.vue')['default']
    PGrid: typeof import('./src/components/global/structure/PGrid.vue')['default']
    PInput: typeof import('./src/components/global/input/PInput.vue')['default']
    PInputField: typeof import('./src/components/global/input/PInputField.vue')['default']
    PList: typeof import('./src/components/global/structure/PList.vue')['default']
    PMetaField: typeof import('./src/components/global/meta/PMetaField.vue')['default']
    PPage: typeof import('./src/components/global/structure/PPage.vue')['default']
    PTable: typeof import('./src/components/global/structure/PTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TForm: typeof import('./src/components/global/structure/TForm.vue')['default']
    TGrid: typeof import('./src/components/global/structure/TGrid.vue')['default']
    TInput: typeof import('./src/components/global/input/TInput.vue')['default']
    TInputField: typeof import('./src/components/global/input/TInputField.vue')['default']
    TList: typeof import('./src/components/global/structure/TList.vue')['default']
    TMetaField: typeof import('./src/components/global/meta/TMetaField.vue')['default']
    TPage: typeof import('./src/components/global/structure/TPage.vue')['default']
    TTable: typeof import('./src/components/global/structure/TTable.vue')['default']
  }
}
