/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TGrid: typeof import('./src/components/global/structure/TGrid.vue')['default']
    TList: typeof import('./src/components/global/structure/TList.vue')['default']
    TPage: typeof import('./src/components/global/structure/TPage.vue')['default']
    TTable: typeof import('./src/components/global/structure/TTable.vue')['default']
  }
}
