[package]
name = "square-api-client"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = { workspace = true }
entity = { path = "../entity" }
domain = { path = "../domain" }
reqwest = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
serde_json = "1.0.151"
tokio = { workspace = true }
wiremock = "0.6.5"
