// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * Represents a Customer DTO.
 */
export type CustomerDto = {
    /**
     * The date of the creation date of this Customer.
     */
    created_at?: string | null;
    /**
     * The date of birth of this Customer.
     */
    date_of_birth?: string | null;
    /**
     * The email address of this Customer.
     */
    email_address?: string | null;
    /**
     * The first name of this Customer.
     */
    first_name?: string | null;
    /**
     * The ID of this Customer.
     */
    id: number;
    /**
     * The last name of this Customer.
     */
    last_name?: string | null;
    /**
     * The date of the last update of this Customer.
     */
    last_updated_at?: string | null;
    /**
     * The nickname of this Customer.
     */
    nickname?: string | null;
    /**
     * The origin of this Customer.
     */
    source?: string | null;
    /**
     * The origin ID of this Customer.
     */
    source_id?: string | null;
};

export type GetAllCustomersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/customers';
};

export type GetAllCustomersResponses = {
    /**
     * The customers were found.
     */
    200: Array<CustomerDto>;
};

export type GetAllCustomersResponse = GetAllCustomersResponses[keyof GetAllCustomersResponses];
