//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "venues")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub country: Option<String>,
    pub language_code: Option<String>,
    pub timezone: Option<String>,
    pub currency: Option<String>,
    #[sea_orm(unique_key = "idx_venues_source_source_id")]
    pub source: Option<String>,
    #[sea_orm(unique_key = "idx_venues_source_source_id")]
    pub source_id: Option<String>,
    pub created_at: DateTime,
    pub last_updated_at: Option<DateTime>,
}

impl ActiveModelBehavior for ActiveModel {}
